os: linux
group: edge

addons:
  apt:
    packages:
    - libdevmapper-dev

language: rust

matrix:
    fast_finish: true
    allow_failures:
        # Allow macro-expansion test to fail
        - rust: nightly
        # Allow audit task to fail
        - env: TASK=audit
    include:

        # MANDATORY CHECKS USING CURRENT DEVELOPMENT COMPILER
        # rustfmt
        - rust: 1.40.0
          before_script:
              - rustup component add rustfmt
          env: TASK=travis_fmt
        # clippy
        - rust: 1.40.0
          before_script:
              - rustup component add clippy
          env: TASK=clippy

        # MANDATORY TESTING USING LOWEST SUPPORTED COMPILER
        # tests
        - rust: 1.38.0
          env: TASK=test


        # MANDATORY TESTING ON STABLE
        # compile
        - rust: stable
          env: TASK=build
        # test
        - rust: stable
          sudo: required
          script: sudo PATH=${TRAVIS_HOME}/.cargo/bin:$PATH make -f Makefile sudo_test
        # Build docs
        - rust: stable
          env: TASK=docs


        # INTERMITTENTLY ALLOWED FAILURES
        # Allowed if a failure occurs after a new Rust release until the
        # failure is addressed.
        # Run clippy on beta to be good Rustaceans
        - rust: beta
          before_script:
              - rustup component add clippy
          env: TASK=clippy


        # ALLOWED FAILURES
        # Run "cargo expand" on rust nightly, in order to see expanded macros
        # that happen to be of interest.
        - rust: nightly
          before_script:
              - rustup component add rustfmt
          env: TASK=expand
        # Run "cargo audit" on rust stable. Make it an allowed failure. It
        # should be an advisory and should not gate our development.
        - rust: stable
          env: TASK=audit

branches:
    only: master

script: make -f Makefile $TASK
