[package]
name = "devicemapper"
version = "0.33.5"
authors = ["Stratis Developers <stratis-devel@lists.fedorahosted.org>"]
description = "A library for using Linux device mapper"
documentation = "https://docs.rs/devicemapper/"
repository = "https://github.com/stratis-storage/devicemapper-rs"
readme = "README.md"
categories = ["os::linux-apis", "api-bindings"]
keywords = ["Linux", "device", "mapper", "libdm", "storage"]
license = "MPL-2.0"
edition = "2021"
rust-version = "1.71.1"  # LOWEST SUPPORTED RUST TOOLCHAIN
exclude = [".clippy.toml", ".githooks/*", ".gitignore", ".github/*", "Makefile"]

[dependencies]
bitflags = "2.3.3"
nix = "0.26.0"
env_logger="0.10.0"
semver = "1.0.0"
serde = "1.0.60"
rand = "0.8.0"
retry = {version = "1.3.1", default-features=false}
lazy_static = "1.2.0"
log = "0.4.14"

[dev-dependencies]
assert_matches = "1.5.0"
libmount = "0.1.11"
loopdev = "0.4.0"
tempfile = "3.0.2"

[dev-dependencies.uuid]
version = "1.0.0"
features = ["v4"]

[dependencies.devicemapper-sys]
version = "0.1.5"
path = "./devicemapper-rs-sys"

[build-dependencies.devicemapper-sys]
version = "0.1.5"
path = "./devicemapper-rs-sys"

[build-dependencies]
semver = "1.0.0"

# FIXME: remove when loopdev dependency lower bound is increased from 0.4.0
[patch.crates-io.loopdev]
git = "https://github.com/mulkieran/loopdev"
branch = "bump-bindgen-reduce-version"
