---
name: devicemapper nightly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 0 3 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  allowed_failures:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - components: cargo
            toolchain: 1.65.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
            task: make -f Makefile audit
          # Allowed because a failure may occur after a new Rust stable
          # version is released.
          - components: clippy
            toolchain: stable
            task: make -f Makefile clippy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          components: ${{ matrix.components }}
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libdevmapper-dev
      - name: Test ${{ matrix.task }} on ${{ matrix.toolchain }} toolchain
        run: ${{ matrix.task }}

  tarpaulin:
    strategy:
      matrix:
        include:
          - toolchain: 1.65.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          components: cargo
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get -y install libdevmapper-dev
      - name: Set toolchain override with sudo
        run: sudo /home/runner/.cargo/bin/rustup override set ${{ matrix.toolchain }}  # yamllint disable rule:line-length
      - name: Run all tests on ${{ matrix.toolchain }} toolchain
        run: sudo PATH=$GITHUB_WORKSPACE/.cargo/bin:$PATH make -f Makefile tarpaulin  # yamllint disable rule:line-length

  checks-with-ci-repo:
    runs-on: ubuntu-20.04
    container:
      image: fedora:36  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for Fedora
        run: >
          dnf install -y
          clang
          curl
          git
          make
          openssl-devel
          python-requests
          python-semantic_version
      - uses: actions-rs/toolchain@v1
        with:
          components: cargo
          toolchain: 1.65.0  # CURRENT DEVELOPMENT RUST TOOLCHAIN
          override: true
      - name: Check out ci repo
        run: git clone https://github.com/stratis-storage/ci.git
      - name: Run comparisons of version specs with available Fedora packages
        # yamllint disable rule:line-length
        run: |
          # -sys
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../devicemapper-rs-sys/Cargo.toml FEDORA_RELEASE=rawhide make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../devicemapper-rs-sys/Cargo.toml FEDORA_RELEASE=f37 make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../devicemapper-rs-sys/Cargo.toml FEDORA_RELEASE=f36 make -f ../../Makefile check-fedora-versions
          # main
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=rawhide IGNORE_ARGS="--ignore-high=loopdev" make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=f37 IGNORE_ARGS="--ignore-high=loopdev" make -f ../../Makefile check-fedora-versions
          COMPARE_FEDORA_VERSIONS=./compare_fedora_versions MANIFEST_PATH=../../Cargo.toml FEDORA_RELEASE=f36 IGNORE_ARGS="--ignore-high=loopdev" make -f ../../Makefile check-fedora-versions
        working-directory: ./ci/dependency_management
